# Copyright (c) 2020 Aleksa Sarai <cyphar@cyphar.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: "Hacktoberfest Anti-Spam"
description: "Detect and close PRs related to Hacktoberfest and mark them as spam."
author: "cyphar"

inputs:
    github_token:
        description: The GitHub token used to create an authenticated client
        default: ${{ github.token }}
        required: false
    aggressive_spam_retaliation:
        description: "Aggressively respond to spam PRs (lock PRs and tag as spam)."
        required: false
        default: false
    all_new_contributors_are_spam:
        description: "Do not give new contributors the benefit of the doubt."
        required: false
        default: false

outputs:
    spam:
        description: "A boolean indicating whether the PR was considered spam."

runs:
    using: "node12"
    main: "index.js"
